### PR TITLE
Fix two bug about single tasks and executor

### LINKED ISSUE #11: 单条插入任务超时时仍然有可能导致统计出错
1. `TaskManager`里面对`singleTasks`超时的情况没有做处理，这样会导致主线程遗漏一部分顶点插入量，然后如果这些`singleTasks`在边插入的过程中完成了，那会被统计到边的结果里面。

    由于超时可能导致有部分记录没有插入，而且用户也不知道，故取消超时时间，将插入机制修改为必须等待插入完成，这样也能避免统计出错。

2. `TaskManager`的`shutdown`部分忽略了`singleExecutor`。

### PR DESCRIPTION
**Pull request by Linary**
1. When a single insert task times out, it may still cause statistical errors.
2. TashManager.shutdown() ignored singleExecutor

Fix #11 
Change-Id: I9a468241f369f4c7e73a95ba9a5772dac90e0ce1

### CODE REVIEW

File: src/main/java/com/baidu/hugegraph/loader/executor/LoadOptions.java [hunk 1]
```diff
@@ -110,6 +110,10 @@ private LoadOptions() {}
                description = "Setting the interval time before retrying")
     public int retryInterval = 10;
 
+    @Parameter(names = {"--continue-when-single-task-timeout"}, arity = 1,
+               description = "Setting the interval time before retrying")
```
Comment (zhoney) [inline src/main/java/com/baidu/hugegraph/loader/executor/LoadOptions.java]: make description matched with name

File: src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java [hunk 2]
```diff
@@ -286,7 +151,7 @@ private void printProgress(String type, long frequency, int batchSize) {
         }
     }
 
-    private void ensurePoolAvailable() {
+    protected void ensurePoolAvailable() {
         while (this.batchService.isShutdown()){
```
Comment (zhoney) [inline src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java]: thread pool can be used immediately after created. no need to wait here.

File: src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java [hunk 3]
```diff
@@ -31,42 +31,30 @@
...
-    private final int futureNum;
-    private final Semaphore available;
-    private final ListeningExecutorService batchService;
-    private final ExecutorService singleExecutor;
-    private final CompletionService<Void> singleService;
-    private final LongAdder singleTasks;
+    protected final int futureNum;
+    protected final Semaphore available;
+    protected final ListeningExecutorService batchService;
+    protected final ExecutorService singleExecutor;
```
Comment (zhoney) [inline src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java]: use multi-thread to improve single-insertion performance

File: src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java [hunk 4]
```diff
@@ -161,7 +151,10 @@ private void createSchema() {
         groovyExecutor.execute(script, client);
     }
 
-    private void loadVertices() {
+    private void loadVertices(LoadSummary summary) {
+        Instant begTime = Instant.now();
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java]: beginTime

File: src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java [hunk 5]
```diff
@@ -88,14 +88,17 @@ public long failureNum() {
...
             // Wait batch task finished
-            this.available.acquire(this.futureNum);
+            this.waitBatchTaskFinished();
             // Wait single task finished
-            this.tryConsume(timeout);
+            this.waitSingleTaskFinished();
+
             if (this.singleTasks.longValue() != 0L) {
-                return false;
+                throw new IllegalStateException(
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java]: E.checkState

File: src/main/java/com/baidu/hugegraph/loader/task/EdgeInsertTask.java [hunk 6]
```diff
@@ -24,9 +24,9 @@
 import com.baidu.hugegraph.loader.executor.LoadOptions;
 import com.baidu.hugegraph.structure.graph.Edge;
 
-public class InsertEdgeTask extends InsertTask<Edge> {
+public class EdgeInsertTask extends InsertTask<Edge> {
 
-    InsertEdgeTask(List<Edge> batch) {
+    EdgeInsertTask(List<Edge> batch) {
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/task/EdgeInsertTask.java]: public

File: src/main/java/com/baidu/hugegraph/loader/task/EdgeInsertTask.java [hunk 7]
```diff
@@ -24,9 +24,9 @@
 import com.baidu.hugegraph.loader.executor.LoadOptions;
 import com.baidu.hugegraph.structure.graph.Edge;
 
-public class InsertEdgeTask extends InsertTask<Edge> {
+public class EdgeInsertTask extends InsertTask<Edge> {
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/task/EdgeInsertTask.java]: InsertionTask

File: src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java [hunk 8]
```diff
@@ -105,37 +108,60 @@ public boolean waitFinished(int timeout) {
         return true;
     }
 
+    private void waitBatchTaskFinished() throws InterruptedException {
+        this.available.acquire(this.futureNum);
+    }
+
+    private void waitSingleTaskFinished() throws InterruptedException {
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java]: waitSingleTasksFinished

File: src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java [hunk 9]
```diff
@@ -105,37 +108,60 @@ public boolean waitFinished(int timeout) {
...
+        long total = this.singleTasks.longValue();
+        for (long i = 0; i < total; i++) {
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java]: i < this.singleTasks.longValue()

**Comment by Linary** [comment]
Already edited

File: src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java [hunk 10]
```diff
@@ -88,19 +88,19 @@ public long failureNum() {
         return this.failureNum.longValue();
     }
 
-    public boolean waitFinished(int timeout) {
+    public boolean waitFinished(String type) {
         try {
             // Wait batch task finished
-            this.available.acquire(this.futureNum);
+            this.batchSemaphore.acquire(options.numThreads);
+            LOG.info("Batch tasks of {} finished", type);
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java]: Batch-mode tasks

File: src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java [hunk 11]
```diff
@@ -207,39 +221,56 @@ private void loadVertex(VertexParser parser) {
...
-                parser.close();
-            } catch (Exception e) {
-                LOG.warn("Failed to close parser for edge source {}", source);
+                EdgeParser parser = new EdgeParser(source, reader);
+                this.loadEdge(parser);
+            } finally {
+                try {
+                    reader.close();
+                } catch (Throwable e) {
+                    LOG.warn("Failed to close parser for edge source {}",
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java]: Failed to close reader

File: src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java [hunk 12]
```diff
@@ -145,55 +138,76 @@ private void resetCounters() {
...
-                if (options.testMode) {
+                if (this.options.testMode) {
                     throw e;
                 }
                 LOG.error("Vertex parse error", e);
                 LOG_PARSE.error(e);
-                if (++this.parseFailureNum >= options.maxParseErrors) {
-                    exitWithInfo("vertices", options.maxParseErrors);
+                if (++this.parseFailureNum >= this.options.maxParseErrors) {
+                    LOG.error("Too many vertices parse error ... Stopping");
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java]: delete it since LOG.error() is called in printError()

File: src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java [hunk 13]
```diff
@@ -207,39 +221,56 @@ private void loadVertex(VertexParser parser) {
...
-                if (options.testMode) {
+                if (this.options.testMode) {
                     throw e;
                 }
                 LOG.error("Edge parse error", e);
                 LOG_PARSE.error(e);
-                if (++this.parseFailureNum >= options.maxParseErrors) {
-                    exitWithInfo("edges", options.maxParseErrors);
+                if (++this.parseFailureNum >= this.options.maxParseErrors) {
+                    LOG.error("Too many edges parse error ... Stopping");
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java]: ditto

File: src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java [hunk 14]
```diff
@@ -88,19 +88,19 @@ public long failureNum() {
...
             // Wait single task finished
-            this.tryConsume(timeout);
-            if (this.singleTasks.longValue() != 0L) {
-                return false;
-            }
+            this.singleSemaphore.acquire(options.numThreads);
+            LOG.info("Single tasks of {} finished", type);
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java]: Single-mode tasks

File: src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java [hunk 15]
```diff
@@ -111,83 +111,95 @@ public void cleanup() {
...
+        LOG.debug("Attempt to shutdown batch tasks executor");
         try {
-            LOG.debug("Attempt to shutdown executor.");
             this.batchService.shutdown();
             this.batchService.awaitTermination(seconds, TimeUnit.SECONDS);
-            this.singleExecutor.shutdown();
-            this.singleExecutor.awaitTermination(seconds, TimeUnit.SECONDS);
         } catch (InterruptedException e) {
-            LOG.error("Tasks is interrupted.");
+            LOG.error("The batch tasks are interrupted");
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java]: ditto, check somewhere else

File: src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java [hunk 16]
```diff
@@ -243,38 +243,38 @@ private void submitEdgesInSingleMode(List<Edge> edges) {
...
+            public void onSuccess(Void result) {
+                singleSemaphore.release();
             }
-        }
+
+            @Override
+            public void onFailure(Throwable t) {
+                singleSemaphore.release();
+            }
+        });
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java]: move line 282 to LoadUtil

File: src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java [hunk 17]
```diff
@@ -46,6 +45,8 @@
 import com.baidu.hugegraph.loader.source.GraphSource;
 import com.baidu.hugegraph.loader.source.VertexSource;
 import com.baidu.hugegraph.loader.task.TaskManager;
+import com.baidu.hugegraph.loader.util.HugeClientWrapper;
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java]: add issue number to commit message

File: src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java [hunk 18]
```diff
@@ -100,43 +107,29 @@ private void parseAndCheckOptions(String[] args) {
     }
 
     private LoadSummary load() {
+        LoadOptions options = LoadOptions.instance();
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java]: remove it, and remove instance() method from class LoadOptions too

**Comment by Linary** [comment]
already edited

File: src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java [hunk 19]
```diff
@@ -57,143 +58,153 @@
...
+        HugeClient client = HugeClientWrapper.get(this.options);
         GroovyExecutor groovyExecutor = new GroovyExecutor();
         groovyExecutor.bind("schema", client.schema());
         String script;
         try {
             script = FileUtils.readFileToString(schemaFile, "UTF-8");
         } catch (IOException e) {
             throw new LoadException("Read schema file '%s' error",
-                                    e, options.schema);
+                                    e, this.options.schema);
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java]: move '%s' to the end

File: src/main/java/com/baidu/hugegraph/loader/util/LoaderUtil.java [hunk 20]
```diff
@@ -19,13 +19,80 @@
...
+    }
+
     public static String backward(long word) {
         StringBuilder backward = new StringBuilder();
         for (int i = 0, len = String.valueOf(word).length(); i <= len; i++) {
             backward.append("\b");
         }
         return backward.toString();
     }
+
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/util/LoaderUtil.java]: move backward() to the bottom of file

File: src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java [hunk 21]
```diff
@@ -58,24 +55,27 @@
...
-        ExecutorService pool = Executors.newFixedThreadPool(this.futureNum);
-        this.batchService = MoreExecutors.listeningDecorator(pool);
-        this.singleExecutor = Executors.newFixedThreadPool(1);
-        this.singleService = new ExecutorCompletionService<>(singleExecutor);
-        this.singleTasks = new LongAdder();
+        this.options = options;
+        this.batchSemaphore = new Semaphore(options.numThreads);
+        this.singleSemaphore = new Semaphore(options.numThreads);
+        this.batchService = MoreExecutors.listeningDecorator(
+                            Executors.newFixedThreadPool(options.numThreads));
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java]: ExecutorUtil.newFixedThreadPool

File: src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java [hunk 22]
```diff
@@ -243,56 +243,51 @@ private void submitEdgesInSingleMode(List<Edge> edges) {
...
 
     private void ensurePoolAvailable() {
-        while (this.batchService.isShutdown()){
-            try {
-                Thread.sleep(100);
-            } catch (Exception ignored) {
-                // That's fine, just continue.
-            }
+        if (this.batchService.isShutdown()) {
+            throw new LoadException("Thread pool has been closed");
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/task/TaskManager.java]: add singleService check too

File: src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java (hunk 19 above)
Comment (Linary) [reply src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java]: Will be modified in the issue #15

File: src/main/java/com/baidu/hugegraph/loader/util/LoaderUtil.java [hunk 23]
```diff
@@ -19,8 +19,75 @@
...
+        System.out.println(message);
+    }
+
+    private static void logAndPrint(String desc, long value) {
+        String msg = String.format("\t%-25s:\t%-20d", desc, value);
+        logAndPrint(msg);
+    }
+
+    public static void printInBackward(long count) {
+        System.out.print(String.format(" %d%s", count,
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/util/LoaderUtil.java]: remove the first space and let backward() return the size without space
remember update loadVertices and loadEdges

File: src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java [hunk 24]
```diff
@@ -57,143 +58,155 @@
...
-                LOG.warn("Failed to close parser for vertex source {}", source);
+                VertexParser parser = new VertexParser(source, reader,
+                                                       this.options);
+                this.loadVertex(parser);
+            } finally {
+                try {
+                    reader.close();
+                } catch (Throwable e) {
+                    LOG.warn("Failed to close reader for vertex source {}",
+                             source, e);
```
Comment (zhoney) [inline src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java]: LOG.warn("Failed to close reader for vertex source {} with exception {}",source, e)

File: src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java [hunk 25]
```diff
@@ -207,39 +220,59 @@ private void loadVertex(VertexParser parser) {
...
-            } catch (Exception e) {
-                LOG.warn("Failed to close parser for edge source {}", source);
+                EdgeParser parser = new EdgeParser(source, reader,
+                                                   this.options);
+                this.loadEdge(parser);
+            } finally {
+                try {
+                    reader.close();
+                } catch (Throwable e) {
+                    LOG.warn("Failed to close reader for edge source {}",
```
Comment (zhoney) [inline src/main/java/com/baidu/hugegraph/loader/HugeGraphLoader.java]: ditto
