### PR TITLE
Fix NPE when json file reload

### LINKED ISSUE #111: 断点续导报错空指针异常
在使用hugegraph-loader 0.14.0 导入数据时，由于部分边的节点不存在，出现顶点插入失败，修改后用断点续导模式会报错空指针异常。
image
执行命令：
 /homehugegraph-loader-0.10.0/bin/hugegraph-loader -g hugegraph -f /home/test/struct-test.json -s /home/test/test.groovy --incremental-mode true --reload-failure true
导入的顶点和边文件都是JSON格式，报错位置出现在header数组转List，是因为断点续导只适用于CSV数据吗？

### PR DESCRIPTION
**Pull request by Linary**
Fix #111

Change-Id: I4f12bcd3ca19464823bc52e5d6b408e4592e1cfc

### CODE REVIEW

File: src/main/java/com/baidu/hugegraph/loader/source/file/FileSource.java [hunk 1]
```diff
@@ -114,7 +114,9 @@ public Compression compression() {
     @Override
     public FileSource asFileSource() {
         FileSource source = new FileSource();
-        source.header(this.header());
+        if (this.header() != null) {
+            source.header(this.header());
+        }
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/source/file/FileSource.java]: prefer to update AbstractSource.header()
```java
    public void header(String[] header) {
        if (header == null) this.header = null;
        else this.header = Arrays.asList(header);
    }
```

File: pom.xml [hunk 2]
```diff
@@ -24,7 +24,7 @@
         <dependency>
             <groupId>com.baidu.hugegraph</groupId>
             <artifactId>hugegraph-client</artifactId>
-            <version>1.8.0</version>
+            <version>1.8.1</version>
```
Comment (javeme) [inline pom.xml]: keep client version compatible

File: src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java [hunk 3]
```diff
@@ -2221,4 +2220,102 @@ public void testLoadIncrementalModeAndReloadFailure()
 
         FileUtils.forceDeleteOnExit(structDir);
     }
+
+    @Test
+    public void testReloadJsonFailureFiles() throws IOException,
```
Comment (javeme) [inline src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java]:
```
[ERROR] testReloadJsonFailureFiles(com.baidu.hugegraph.loader.test.functional.HDFSLoadTest)  Time elapsed: 0.517 s  <<< ERROR!
com.baidu.hugegraph.loader.exception.LoadException: Failed to parse graph struct description file 'target/test-classes/reload_json_failure_files/struct_hdfs.json'
Caused by: java.lang.IllegalArgumentException: The core_site_path can't be empty
```
