### PR TITLE
Fix nullable key in mapping field can't work

### LINKED ISSUE #63: Bug: nullable key in mapping field can't work
schema define 

```
schema.vertexLabel("person").properties("name", "city").primaryKeys("name").nullableKeys("city").ifNotExist().create();
```

struct 

```
{
  "vertices": [
    {
      "label": "person",
      "input": {
        "type": "${source_type}",
        "path": "${store_path}/vertex_person.csv",
        "format": "CSV",
        "charset": "UTF-8"
      },
      "mapping": {
        "姓名": "name",
        "城市": "city"
      },
      "null_values": ["-", "--", "----"]
    }
  ]
}
```

vertex file

```
姓名,城市
marko,-
vadas,--
josh,----
```

After loaded, use RESTful API query vertices, will see that 

```
{
"id": "1:marko",
"label": "person",
"type": "vertex",
    "properties":{
        "name": "marko",
        "city": "-"
    }
}
...
```

### PR DESCRIPTION
**Pull request by Linary**
Change-Id: I87d47ef14334a8326ce96e4def4571a0ed31e5fd

Fix #63

### CODE REVIEW

File: src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java [hunk 1]
```diff
@@ -589,6 +589,40 @@ public void testIgnoreNullValueColumns() {
...
+        Assert.assertEquals(3, vertices.size());
+
+        for (Vertex vertex : vertices) {
+            if (vertex.property("name").equals("marko")) {
+                Assert.assertNull(vertex.property("age"));
+                Assert.assertNull(vertex.property("city"));
+            } else if (vertex.property("name").equals("vadas")) {
+                Assert.assertNull(vertex.property("age"));
+                Assert.assertEquals("Hongkong", vertex.property("city"));
+            } else if (vertex.property("name").equals("josg")) {
```
Comment (zhoney) [inline src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java]: josh

File: src/main/java/com/baidu/hugegraph/loader/builder/ElementBuilder.java [hunk 2]
```diff
@@ -113,7 +113,7 @@ public void close() throws Exception {
             Iterator<Map.Entry<String, Object>> itor = keyValues.entrySet()
                                                                 .iterator();
             itor.forEachRemaining(entry -> {
-                String key = entry.getKey();
+                String key = source().mappingField(entry.getKey());
```
Comment (javeme) [inline src/main/java/com/baidu/hugegraph/loader/builder/ElementBuilder.java]: this.source()
