### PR TITLE
Fix parser exception cannot be caught

### LINKED ISSUE #73: Bug: ParserException cannot be caught correctly
### Excepted behavior : 
If a line's column length doesn't match with header length, it should thow a ParserException and skip this line util > `max-parser-error`

### Actual behavior :
If meet ParserException, the loader will stop directlly & get stuck

### PR DESCRIPTION
**Pull request by imbajin**
Fix parser exception cannot be caught

The reason of the problem is that the difference between new & old version of `hasNext()` & `next()`, the new version's `hasNext()` used `parse()` without exception caught.

fix #73

### CODE REVIEW

**Comment by Linary** [comment]
You can add one test case, set testMode=false, and expect no exception.

**Comment by imbajin** [comment]
> 
> 
> You can add one test case, set testMode=false, and expect no exception.

OK, make up later~

File: src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java [hunk 1]
```diff
@@ -31,7 +31,9 @@
 import org.junit.AfterClass;
 import org.junit.Before;
 import org.junit.BeforeClass;
+import org.junit.Rule;
```
Comment (Linary) [inline src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java]: remove unused import

File: src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java [hunk 2]
```diff
@@ -1246,4 +1248,25 @@ public void testLZ4FramedCompressFile() {
         };
         HugeGraphLoader.main(args);
     }
+
+    @Test
+    public void testParserNotThrowException() {
+        // Here are 3 parser errors, and except no exception thrown
```
Comment (Linary) [inline src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java]: 2 parse errors, except -> expect

File: src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java [hunk 3]
```diff
@@ -1246,4 +1248,25 @@ public void testLZ4FramedCompressFile() {
...
+
+        String[] args = new String[]{
+                "-f", configPath("too_few_columns/struct.json"),
+                "-s", configPath("too_few_columns/schema.groovy"),
+                "-g", GRAPH,
+                "-h", SERVER,
+                "--num-threads", "2",
+                "--max-parse-errors", "4"
+        };
+        // TODO: Fix the JVM will exit directly if this test throws exception
```
Comment (Linary) [inline src/test/java/com/baidu/hugegraph/loader/test/functional/FileLoadTest.java]: remove TODO, due to "--max-parse-errors" = "4"

**Comment by Linary** [comment]
remember to rebase latest commit
